### ISSUE TITLE
Unable to connect to output (no mod-monitor ports)

### ISSUE THREAD

**Issue by mindhog** [moddevices/mod-ui#112]
When running on a PC according to the instructions in the README, connections seem to work fine except when I try to connect an effect to one of the output ports.  In that case, nothing happens and I see the following output on the server:

    INFO:tornado.access:200 GET /ping?_=1609772547309 (127.0.0.1) 0.52ms                                                                                          
    DEBUG:root:[host] popped from queue: connect effect_0:out mod-monitor:in_1                                                                                    
    DEBUG:root:[host] sending -> connect effect_0:out mod-monitor:in_1                                                                                            
    DEBUG:root:[host] received <- 'resp -205\x00'                                                                                                                 
    ERROR: backend failed to connect ports: '/graph/metal_head/out' => '/graph/playback_1'                                                                        
    INFO:tornado.access:200 GET /effect/connect//graph/metal_head/out,/graph/playback_1?_=1609772547310 (127.0.0.1) 0.89ms

I can't find anything to indicate which program is supposed to publish the mod-monitor ports.  The MOD_LIB_ISO and MOD_APP environment variables seem to allow you to replace these with the system:* ports but they also seem to break the host connection for me.

How should this work?

(BTW, aside from this everything appears to be working fine and this UI is fairly awesome!!)

**Comment by falkTX** [comment]
the monitor client is part of mod-host.

it should load by default, that was the idea, but there is a jack2 bug that crashes the whole server on versions < 1.9.13
since debian and ubuntu still have 1.9.12, it is too risky to push that to everyone.

you can workaround this by running "jack_load mod-monitor" once per boot, assuming you installed mod-host before.

**Comment by mindhog** [comment]
Thanks, should this be in the instructions in the README?

**Comment by falkTX** [comment]
The README needs some serious work, a whole bunch of new tagged releases too.
Lets see about this after the Dwarf units are out and v1.10 OS image stabilizes.
I do want to make releases for all these things, in due time. Likely late in January. (a license change/update is long overdue as well, to AGPL)

**Comment by mindhog** [comment]
Cool.  With regards to licensing, be aware that AGPL is a deal-breaker in some contexts (for example, use of AGPL code is [completely verboten at Google](https://opensource.google/docs/using/agpl-policy/)).

Also, if you'll accept a pull request, I'm happy to send one to update the README regarding just this issue.  If you prefer, I'm also happy to not bother you further immediately prior to the Dwarf release :-)

**Comment by falkTX** [comment]
> for example, use of AGPL code is [completely verboten at Google](https://opensource.google/docs/using/agpl-policy/)

seems like a win to me :)



> Also, if you'll accept a pull request, I'm happy to send one to update the README regarding just this issue. If you prefer, I'm also happy to not bother you further immediately prior to the Dwarf release :-)

PRs are very welcome, specially straight-forward ones like these.

**Comment by mindhog** [comment]
Closing this as the documentation fix is in place.
