### ISSUE TITLE
Can't load store plugins during local development / no API key

### ISSUE THREAD

**Issue by alex-hofsteede** [moddevices/mod-ui#127]
Hi there

In running MOD-UI on my macbook, I am seeing the following on startup. 

```
WARN: Missing file /Volumes/NONAME/dev/mod_devices/mod-ui/data/mod_api_key.pub with the public API KEY
```

When I visit the plugin store in the local web UI, it makes a request to `https://api-dev.moddevices.com/v2/lv2/plugins` and receives an empty `[]` response. I assume these 2 things are related, but I can't find any info on getting an API key in the build docs or forums. I can compile plugins locally and have them show up in the UI.

**Comment by falkTX** [comment]
This is intentional, the cloud/store is restricted in its usage to MOD units, the authentication requires specific hardware for this to work with the device providing a public key and the cloud side having the private key.
