### ISSUE TITLE
Abandonned and unmaintened pycrypto -> use pycryptodome instead.

### ISSUE THREAD

**Issue by jujudusud** [moddevices/mod-ui#128]
Hi here,

Since pycrypto is unmaintened and forked to pycryptodome, We should use it as a requirement to build mod-ui.

Please take a look at: [pycryptodome](https://github.com/Legrandin/pycryptodome).

Do you want me to provide a PR?
We only have to change requirement.txt file with the new pycryptodome.

**Comment by jujudusud** [comment]
AFAIK, [PyCryptodome 3.9.9 (Nov 2, 2020)](https://pypi.org/project/pycryptodome/3.9.9/) does support Python 3.4.
I don't know if this is sufficient to be use in MOD.

**Comment by falkTX** [comment]
This is fixed by fc843bde9f0b23cfab40c3bcc133378342a8a070
