### ISSUE TITLE
Midi Port not showing up in UI and web backend

### ISSUE THREAD

**Issue by rominator1983** [moddevices/mod-ui#131]
I think that this repository is the right place to put this.
I am trying to connect some MIDI devices. I have a Steinberg UR22 MKII with MIDI ports on the back and two USB-MIDI devices for input.
When starting up mod-host I see that my MIDI hardware ports get connected to the virtual "midi_in" of mod-host in qjackctl:
![image](https://user-images.githubusercontent.com/13437300/198124395-5757265b-a108-4a47-a48e-0b22b3cecb8d.png)

I have set up everything in Ubuntu studio controls to use a2jmidid which I really do not know if it is right.
Anyhow mod-ui does not show me MIDI devices in the "MIDI PORTS" windows (only the option for aggregated or separate inputs but no device list).
![image](https://user-images.githubusercontent.com/13437300/198125013-fe4276d2-98e0-43ad-b394-283445995c7c.png)

The main problem here is of course that I do not have a MIDI port to connect any MIDI effect to in the web UI on the left side:
![image](https://user-images.githubusercontent.com/13437300/198124958-55125e87-72e6-40eb-9f69-b800c63bf3e7.png)

Calling the URL `http://localhost:8888/jack/get_midi_devices` gives me the following: `{"devsInUse": [], "devList": [], "names": {}, "midiAggregatedMode": false}` which I suppose is not what I want since there should be some devices here.

Since I can see that mod-host does its stuff when starting up I suppose something in MOD-UI does not work quite the way I would want.

I am using latest host and ui as of today.

I tried to follow the code in MOD-UI to see what is going on but I don't quite see what could be wrong or how I could even add some troubleshooting output on the console that helps me somehow.

**Comment by falkTX** [comment]
MOD uses -X seq jackd option for MIDI, a2jmidid is not supported.
Switch to that and things will generally work.

**Comment by rominator1983** [comment]
@falkTX let me tell you how great it is to have such quick feedback from you!
I reconfigured the MIDI Driver in qjackctl to "seq" but got nothing working until I eventually tried out the option "Enable JACK D-Bus interface" in qjackctl. Now I see the MIDI ports in the UI as one would expect.

Unfortunately this now broke the "Studio Controls" of Ubuntu Studio somehow and I now have to start jack using qjackctl myself everytime.

For anyone having troubles getting things to work this are my settings:
![image](https://user-images.githubusercontent.com/13437300/198141773-94460ebb-7e21-450e-8be5-8bfe20bf4aec.png)

**Comment by falkTX** [comment]
It should work with or without dbus, on MOD units jackd is used without dbus so I know that part works.
Getting things to work with a2jmidid is out of scope.

**Comment by rominator1983** [comment]
I hear you. Well something must be different then because if I turn that thing off I have no Midi hardware jack devices in qjackctl. I can only create Alsa MIDI devices but that don't with either because that can't connect to jack Midi devices at all.

**Comment by falkTX** [comment]
use jackd from the terminal instead of qjackctl then, should be something like...
```
jackd -R -P 80 -d alsa -d hw:Rubix22 -r 48000 -p 128 -n 3 -X seq
```

**Comment by rominator1983** [comment]
I thought I could avoid that ^^ Thank you again.
For anyone stumbling over this. I ended up with the following command line for starting jack: `jackd -R -P 80 -d alsa -d hw:1,0 -r 96000 -p 256 -n 2 -X seq`

This yields to the following working connections and set up devices by jack and MOD (qjackctl, Graph)
![image](https://user-images.githubusercontent.com/13437300/198562080-5a7782d1-ad12-482f-a57f-2692882de4be.png)
