### ISSUE TITLE
exclude given ports from GUI

### ISSUE THREAD

**Issue by x42** [moddevices/mod-ui#3]
Ports with
*   http://lv2plug.in/ns/ext/port-props#notOnGUI
*   http://lv2plug.in/ns/lv2core#freeWheeling
*   http://lv2plug.in/ns/lv2core#reportsLatency

should not be included in the UI

**Comment by falkTX** [comment]
ports with certain designations should also not be shown, such as:
*   http://lv2plug.in/ns/lv2core#latency
*   http://lv2plug.in/ns/ext/parameters#sampleRate

**Comment by falkTX** [comment]
all these ports are not shown on MOD UI anymore.
if there's some I missed let me know.
