### ISSUE TITLE
Build problem on Fedora 23

### ISSUE THREAD

**Issue by ycollet** [moddevices/mod-ui#36]
I followed the instruction from the README file.
When I start the server, I have the following error message:
Traceback (most recent call last):
  File "./server.py", line 24, in <module>
    from mod import webserver
  File "/home/collette/repositories/LV2/portalmod/mod-ui/mod/webserver.py", line 49, in <module>
    from mod.session import SESSION
  File "/home/collette/repositories/LV2/portalmod/mod-ui/mod/session.py", line 33, in <module>
    from mod.development import FakeHost, FakeHMI
  File "/home/collette/repositories/LV2/portalmod/mod-ui/mod/development.py", line 21, in <module>
    from mod.host import Host
  File "/home/collette/repositories/LV2/portalmod/mod-ui/mod/host.py", line 39, in <module>
    from mod.utils import charPtrToString
  File "/home/collette/repositories/LV2/portalmod/mod-ui/mod/utils.py", line 134, in <module>
    utils = cdll.LoadLibrary(tryPath2)
  File "/usr/lib64/python3.4/ctypes/__init__.py", line 424, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python3.4/ctypes/__init__.py", line 346, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/collette/repositories/LV2/portalmod/mod-ui/mod/../utils/libmod_utils.so: cannot open shared object file: No such file or directory

If I compile the so file in the utils directory:

$ make
g++ utils_lilv.cpp -Wall -Wextra -Wshadow -std=gnu++0x -fPIC -O3 -I/usr/include/lilv-0 -I/usr/include/sratom-0 -I/usr/include/sord-0 -I/usr/include/serd-0  -c -o utils_lilv.cpp.o
utils_lilv.cpp: Dans la fonction ‘void _refresh()’:
utils_lilv.cpp:561:83: erreur: ‘lilv_file_uri_parse’ was not declared in this scope
             lilvparsed = lilv_file_uri_parse(lilv_node_as_uri(bundlenode), nullptr);
                                                                                   ^
utils_lilv.cpp:568:37: erreur: ‘lilv_free’ was not declared in this scope
                 lilv_free(lilvparsed);
                                     ^
utils_lilv.cpp:574:33: erreur: ‘lilv_free’ was not declared in this scope
             lilv_free(lilvparsed);
                                 ^
utils_lilv.cpp: Dans la fonction ‘const PluginInfo_Mini& _get_plugin_info_mini(const LilvPlugin*, const NamespaceDefinitions_Mini&)’:
utils_lilv.cpp:877:36: erreur: ‘lilv_free’ was not declared in this scope
             lilv_free((void*)resdir);
                                    ^
utils_lilv.cpp:878:79: erreur: ‘lilv_file_uri_parse’ was not declared in this scope
             resdir = lilv_file_uri_parse(lilv_node_as_string(resdirn), nullptr);
                                                                               ^
utils_lilv.cpp:890:32: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free((void*)resdir);
                                ^
utils_lilv.cpp:896:100: erreur: ‘lilv_file_uri_parse’ was not declared in this scope
                 info.gui.screenshot = lilv_file_uri_parse(lilv_node_as_string(modgui_scrn), nullptr);
                                                                                                    ^
utils_lilv.cpp:906:100: erreur: ‘lilv_file_uri_parse’ was not declared in this scope
                 info.gui.thumbnail = lilv_file_uri_parse(lilv_node_as_string(modgui_thumb), nullptr);
                                                                                                    ^
utils_lilv.cpp: Dans la fonction ‘const PluginInfo& _get_plugin_info(const LilvPlugin*, const NamespaceDefinitions&)’:
utils_lilv.cpp:942:70: erreur: ‘lilv_file_uri_parse’ was not declared in this scope
     const char* const bundle    = lilv_file_uri_parse(bundleuri, nullptr);
                                                                      ^
utils_lilv.cpp:1332:41: erreur: ‘lilv_free’ was not declared in this scope
                     lilv_free(lilvparsed);
                                         ^
utils_lilv.cpp:1337:37: erreur: ‘lilv_free’ was not declared in this scope
                 lilv_free(lilvparsed);
                                     ^
utils_lilv.cpp:1375:36: erreur: ‘lilv_free’ was not declared in this scope
             lilv_free((void*)resdir);
                                    ^
utils_lilv.cpp:2141:28: erreur: ‘lilv_free’ was not declared in this scope
     lilv_free((void*)bundle);
                            ^
utils_lilv.cpp: Dans la fonction ‘const PedalboardInfo_Mini& _get_pedalboard_info_mini(const LilvPlugin*, LilvWorld*, const LilvNode*, const LilvNode*, const LilvNode*)’:
utils_lilv.cpp:2190:77: erreur: ‘lilv_file_uri_parse’ was not declared in this scope
         info.bundle = lilv_file_uri_parse(lilv_node_as_string(node), nullptr);
                                                                             ^
utils_lilv.cpp: Dans la fonction ‘void _clear_plugin_info(PluginInfo&)’:
utils_lilv.cpp:2307:35: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free((void*)info.name);
                                   ^
utils_lilv.cpp:2309:37: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free((void*)info.binary);
                                     ^
utils_lilv.cpp:2327:53: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free((void*)info.gui.resourcesDirectory);
                                                     ^
utils_lilv.cpp:2329:47: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free((void*)info.gui.iconTemplate);
                                               ^
utils_lilv.cpp:2331:51: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free((void*)info.gui.settingsTemplate);
                                                   ^
utils_lilv.cpp:2333:45: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free((void*)info.gui.javascript);
                                             ^
utils_lilv.cpp:2335:45: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free((void*)info.gui.stylesheet);
                                             ^
utils_lilv.cpp:2337:45: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free((void*)info.gui.screenshot);
                                             ^
utils_lilv.cpp:2339:44: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free((void*)info.gui.thumbnail);
                                            ^
utils_lilv.cpp: Dans la fonction ‘void _clear_plugin_info_mini(PluginInfo_Mini&)’:
utils_lilv.cpp:2440:45: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free((void*)info.gui.screenshot);
                                             ^
utils_lilv.cpp:2442:44: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free((void*)info.gui.thumbnail);
                                            ^
utils_lilv.cpp: Dans la fonction ‘void _clear_pedalboard_info(PedalboardInfo&)’:
utils_lilv.cpp:2456:56: erreur: ‘lilv_free’ was not declared in this scope
             lilv_free((void*)info.connections[i].source);
                                                        ^
utils_lilv.cpp:2488:62: erreur: ‘lilv_free’ was not declared in this scope
             lilv_free((void*)info.hardware.midi_ins[i].symbol);
                                                              ^
utils_lilv.cpp:2501:63: erreur: ‘lilv_free’ was not declared in this scope
             lilv_free((void*)info.hardware.midi_outs[i].symbol);
                                                               ^
utils_lilv.cpp: Dans la fonction ‘void _clear_pedalboard_info_mini(PedalboardInfo_Mini&)’:
utils_lilv.cpp:2518:37: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free((void*)info.bundle);
                                     ^
utils_lilv.cpp: Dans la fonction ‘void cleanup()’:
utils_lilv.cpp:2706:26: erreur: ‘lilv_free’ was not declared in this scope
     lilv_free(_uri_parsed);
                          ^
utils_lilv.cpp: Dans la fonction ‘const char* const* remove_bundle_from_lilv_world(const char*)’:
utils_lilv.cpp:2886:83: erreur: ‘lilv_file_uri_parse’ was not declared in this scope
             tmp = (char*)lilv_file_uri_parse(lilv_node_as_uri(bundlenode), nullptr);
                                                                                   ^
utils_lilv.cpp:2893:30: erreur: ‘lilv_free’ was not declared in this scope
                 lilv_free(tmp);
                              ^
utils_lilv.cpp:2898:26: erreur: ‘lilv_free’ was not declared in this scope
             lilv_free(tmp);
                          ^
utils_lilv.cpp: Dans la fonction ‘const PedalboardInfo_Mini* const* get_all_pedalboards()’:
utils_lilv.cpp:3181:26: erreur: ‘lilv_free’ was not declared in this scope
     lilv_free(rdftypenode);
                          ^
utils_lilv.cpp: Dans la fonction ‘const PedalboardInfo* get_pedalboard_info(const char*)’:
utils_lilv.cpp:3214:37: erreur: ‘lilv_world_load_specifications’ was not declared in this scope
     lilv_world_load_specifications(w);
                                     ^
utils_lilv.cpp:3215:37: erreur: ‘lilv_world_load_plugin_classes’ was not declared in this scope
     lilv_world_load_plugin_classes(w);
                                     ^
utils_lilv.cpp:3349:98: erreur: ‘lilv_file_uri_parse’ was not declared in this scope
                     char* full_instance = lilv_file_uri_parse(lilv_node_as_string(block), nullptr);
                                                                                                  ^
utils_lilv.cpp:3436:44: erreur: ‘lilv_free’ was not declared in this scope
                     lilv_free(full_instance);
                                            ^
utils_lilv.cpp:3479:87: erreur: ‘lilv_file_uri_parse’ was not declared in this scope
                 char* tailstr = lilv_file_uri_parse(lilv_node_as_string(tail), nullptr);
                                                                                       ^
utils_lilv.cpp:3570:90: erreur: ‘lilv_file_uri_parse’ was not declared in this scope
                             char* portsym = lilv_file_uri_parse(port_uri.c_str(), nullptr);
                                                                                          ^
utils_lilv.cpp:3599:90: erreur: ‘lilv_file_uri_parse’ was not declared in this scope
                             char* portsym = lilv_file_uri_parse(port_uri.c_str(), nullptr);
                                                                                          ^
utils_lilv.cpp: Dans la fonction ‘StatePortValue* get_state_port_values(const char*)’:
utils_lilv.cpp:3813:73: erreur: ‘lilv_state_emit_port_values’ was not declared in this scope
         lilv_state_emit_port_values(lstate, lilv_set_port_value, &values);
                                                                         ^
utils_lilv.cpp: Dans la fonction ‘const char* file_uri_parse(const char*)’:
utils_lilv.cpp:3897:30: erreur: ‘lilv_free’ was not declared in this scope
         lilv_free(_uri_parsed);
                              ^
utils_lilv.cpp:3899:55: erreur: ‘lilv_file_uri_parse’ was not declared in this scope
     _uri_parsed = lilv_file_uri_parse(fileuri, nullptr);
                                                       ^
Makefile:21: recipe for target 'utils_lilv.cpp.o' failed
make: *** [utils_lilv.cpp.o] Error 1

Lilv version on fedora 23: 0.20.0

**Comment by falkTX** [comment]
You're correct that "make" needs to be run on the utils dir.

the build error you get is because you're using an old version of lilv.
you need to updated it.
not sure exactly what version is required, but since there's been a lot of changes in the latest git version I recommend going with that.

**Comment by ycollet** [comment]
Thanks, I will install a recent version of lilv from source.

Best regards,

YC

**Comment by SpotlightKid** [comment]
I just stumbled on that `libutils` too. You should add this to the installation instructions in the readme:

```
Compile `libmod_utils`:

    (cd utils; make;)

**Comment by ycollet** [comment]
For this to work, you need a recent version of lilv library.

**Comment by SpotlightKid** [comment]
Ah, ok. I always do. ;)
