### ISSUE TITLE
[feature request] plugin store: turn URI's that begin with http into hyperlinks

### ISSUE THREAD

**Issue by ericfont** [moddevices/mod-ui#41]
When viewing a plugin's info popup, only homepages are currently hyperlinked.  I'd like for the URI's to be hyperlinked as well.

**Comment by falkTX** [comment]
No, URIs are identifiers and not real URLs.
Most of the plugin URIs lead to nowhere.

**Comment by ericfont** [comment]
ok, thanks for clarifying.  I mistook those URI's for valid URL's.
