### ISSUE TITLE
Can't save *NEW* pedalboard => "Nothing to Save"

### ISSUE THREAD

**Issue by jofemodo** [moddevices/mod-ui#44]
After commit "c3391e5f58e00a1c9737bdec6ceacb0f699611e4", when trying to save a NEW pedalboard, it gives the message "Nothing to Save" and the "Save/Save as" dialog is not opened.

**Comment by falkTX** [comment]
master is the development branch, while it runs there might be issues like this.
Use one of the hotfix branches for something more stable.
Latest one is hotfix-1.2.

That being said, thanks for the report.
I've noticed the issue too, will fix it soon.
