### ISSUE TITLE
MIDI unlearning doesn't work

### ISSUE THREAD

**Issue by jofemodo** [moddevices/mod-ui#45]
When trying to un-learn an assigned controller selecting "None" from the combo in the popup and clicking "Save", it doesn't work. The controller is "re-enabled in the GUI, but the MIDI-CC remains linked to the controller and it can't be assigned to another one. The only way to "free" an assigned MIDI-CC is re-learning the controller and assigning a different one.

I'm testing with the later version from repository.

**Comment by falkTX** [comment]
> I'm testing with the later version from repository.

You mean latest?
(latest git commit I assume..)

**Comment by jofemodo** [comment]
Ups!! Yes, sorry ...

**Comment by jofemodo** [comment]
It works like a charm! Thanks!
