### ISSUE TITLE
Control values of knobs sent as integer

### ISSUE THREAD

**Issue by jpcima** [moddevices/mod-ui#63]
On a real-valued control manipulated by knob on the GUI, only integer steps of values are sent to the effect, as if converted and truncated by `(int)` cast.
The problem happened running on jack with a mod-host internal client.

How I trigger the problem:
- install caps-lv2
- run mod-ui at port 9000
- instantiate AmpVTS in the web UI
- connect ports in Jack
- rotate some knobs either on the front or settings page: "Gain", "Power".

Result: the UI shows real values on the display in 0...1 range, but in effect the plugin received just either 0, or 1 when the knob was rotated at the far right of the range.
There was no such problem using Carla as host on the same plugin.

Forum thread on topic of this problem:
https://forum.moddevices.com/t/making-a-plugin-need-help-with-mod-ui/2734/3

Detail of the software used:
- `mod-host-git 0.10.6.r272.387630e-1`
- `mod-ui-git 0.99.8.r2220.03ede9bb-1`
- `jack2 1.9.12-6`
- `python 3.7.0-3`
- `chromium 69.0.3497.92-1`
- `Linux quad 4.16.18-rt12-1-rt #1 SMP PREEMPT RT Fri Sep 14 11:01:38 CEST 2018 x86_64 GNU/Linux`

**Comment by brummer10** [comment]
mm, any of my plugs using float controls in the range 0 . . . 1 without any issue on the MOD.

**Comment by jpcima** [comment]
I have retried after an update of both `mod-ui` and `mod-host`, and the controls have worked fine.
I close this issue.

mod-host `e7a0668`, mod-ui `bcc62413`
