### ISSUE TITLE
Outputs cannot be connected from Web UI

### ISSUE THREAD

**Issue by cibban** [moddevices/mod-ui#65]
I have tried this on two different computers, one running AVL and one running Ubuntu Studio. With the mod-app I can connect items to the outputs just fine but when I run the backend with the Web UI the outputs are disconnected, even though the pedalboard is saved, and can't be re-connected.

**Comment by jkbd** [comment]
Have you started the UI like this:
```
MOD_APP=1 MOD_LIVE_ISO=1 ./server.py
```
?
The ports that Jack connects are handed over as strings. Without the above environment variables set the wrong output port names are assumed and connection fails.
Please comment if this solves your problem.

**Comment by cibban** [comment]
I installed mod-control, mod-iso, mod-app, mod-host and mod-ui with all dependencies using my package manager and the KXStudio mod repositories, so I haven't been running the python scripts directly.

I have tried running the web UI from the mod-control application as well as "mod-ui" on the command line, but the latter fails to connect to jack. Connection is refused but the jack log doesn't give much info as to why. Running from the control panel works but the playback ports are not connected.

I had a look at the jack log and the difference is that host-ui tries to connect to the non-existent ports "mod-monitor:in_1" and "mod-monitor:in_2" while mod-app correctly connects to "system:playback_1" and "system:playback_1".

I have tried exporting the variables you mention before running but it makes no difference. I also tried setting MOD_DEV_ENVIRONMENT and MOD_DEV_HOST to 0, as suggested by FalkTX on the forum.

What I'm trying to do to run mod-ui headless on an old laptop with a broken screen and control it from another computer or a smartphone. I know this is not the purpose of this project so my expectations are low but it would be fun to get it up and running, proving the point to my Mac loving band members that you can actually do cool stuff with linux too. :)

**Comment by cibban** [comment]
Actually, it would be optimal to run mod-host stand-alone with a preset and just control it with midi, but I can't figure out how to even get mod-host to do anything and the documentation is either sparse or my google-fu is forever gone.

**Comment by jkbd** [comment]
I run
```
$ start-jack-the-way-you-like.sh
$ cd $GITHUB/mod-host
$ ./mod-host -n -p 5555 -f 5556
...
mod-host ready!
```
Then in another terminal
```
$ cd $GITHUB/mod-ui
$ source modui-env/bin/activate
(modui-env) $ MOD_APP=1 MOD_LIVE_ISO=1 MOD_DEV_ENVIRONMENT=0 ./server.py
```
and I can connect to the system outputs. My first system output is called `system:playback_1`.

You can't control mod-host via MIDI. But since you are looking for a LV2 host, have you tried [Carla](https://github.com/falkTX/Carla)?
You can run it headless with the `--no-gui` option. I would expect `carla-control` to be the remote companion. Unfortunately the `--help` option seems to be copy/paste and does not give me a clue. Most likely @falkTX could help with the usage.

**Comment by cibban** [comment]
You are entirely right that what I'm actually looking for is a headless lv2 host. I got kind of stuck on the fact that I'm using it with an electric guitar and didn't realize that I has the solution _literally_ right before my eyes since I use Carla all the time with a synth for spontaneous noodling on my midi keyboard and a system wide limiter to keep me from getting evicted. :) Thank you so much for that insight! I know exactly what to do now.

**Comment by jkbd** [comment]
Cool! You're welcome!
