### ISSUE TITLE
Couldn’t address parameter, not allowed

### ISSUE THREAD

**Issue by MaxPayne86** [moddevices/mod-ui#87]
Main board: custom Linux board running mod-duo, a-la Zynthian
CC board: Arduino/Genuino Uno running Pot example

Issue:
CC controller is recognized, however when trying to map a random (a casual parameter from whatever effect), I got the message **Bug! Couldn’t address parameter, not allowed**. The message is printed into **mod-ui** sources **html/js/desktop.js**. I cannot tell if the problem is on mod-ui or in the cc-arduino-lib, please see companion issue https://github.com/moddevices/cc-arduino-lib/issues/4

Mod-ui log:
NOTICE: Now scanning plugin 'http://moddevices.com/plugins/caps/AutoFilter'...
NOTICE: Finished scanning 'http://moddevices.com/plugins/caps/AutoFilter'
INFO:tornado.access:200 GET /effect/get?uri=http%3A%2F%2Fmoddevices.com%2Fplugins%2Fcaps%2FAutoFilter (10.10.10.208) 19.61ms
INFO:tornado.access:200 GET /effect/file/iconTemplate?uri=http%3A//moddevices.com/plugins/caps/AutoFilter&v=0_24_9_0&r=1565336710 (10.10.10.208) 11.32ms
INFO:tornado.access:200 GET /effect/file/stylesheet?uri=http%3A//moddevices.com/plugins/caps/AutoFilter&v=0_24_9_0&r=1565336710 (10.10.10.208) 12.93ms
DEBUG:root:[host] popped from queue: add http://moddevices.com/plugins/caps/AutoFilter 1
DEBUG:root:[host] sending -> add http://moddevices.com/plugins/caps/AutoFilter 1
DEBUG:root:[host] received <- 'resp 1\x00'
INFO:tornado.access:200 GET /effect/add//graph/AutoFilter?x=1880.3125&y=504.09375&uri=http%3A//moddevices.com/plugins/caps/AutoFilter&_=1566478909589 (10.10.10.208) 84.12ms
INFO:tornado.access:200 GET /effect/get?uri=http%3A//moddevices.com/plugins/caps/AutoFilter (10.10.10.208) 17.03ms
INFO:tornado.access:200 GET /ping?_=1566478909590 (10.10.10.208) 5.67ms
INFO:tornado.access:200 GET /ping?_=1566478909591 (10.10.10.208) 5.44ms
INFO:tornado.access:200 GET /ping?_=1566478909592 (10.10.10.208) 5.54ms
DEBUG:root:[host] idle? -> 1
DEBUG:root:[host] popped from queue: cc_map 1 frequency 1 0 "Frequency" 2555.000000 20.000000 3400.000000 33 "Hz" 0
DEBUG:root:[host] sending -> cc_map 1 frequency 1 0 "Frequency" 2555.000000 20.000000 3400.000000 33 "Hz" 0
DEBUG:root:[host] received <- 'resp -401\x00'

**Comment by falkTX** [comment]
mod-host returns 401, which means control chain support was not compiled in (in mod-host).

**Comment by MaxPayne86** [comment]
> mod-host returns 401, which means control chain support was not compiled in (in mod-host).

Hi falkTX,

do I have to compile mod-host with

`-DHAVE_CONTROLCHAIN`

option?

**Comment by falkTX** [comment]
not exactly. you need to build the cc-client library.
see https://github.com/moddevices/mod-host/blob/master/Makefile#L65

**Comment by MaxPayne86** [comment]
Hi falkTX and thanks, I've seen **libcc_client.so** is compiled in cc-master package, I'm going to rebuild mod-host with this dependency into the sysroot folder (where pkg-config will look at it) and retry. Is up to you if you want to close this issue or waiting for my tests (I could reopen if it doesn't work...)

**Comment by MaxPayne86** [comment]
@falkTX I have errors during building of mod-host. It seems the published version of cc-master has some problems. Please see related issue https://github.com/moddevices/cc-master/issues/3.
