### ISSUE TITLE
Crash of mod-ui when moving from midi separated mode to midi aggregated mode

### ISSUE THREAD

**Issue by MaxPayne86** [moddevices/mod-ui#96]
Hello,

I'm using very recent versions of mod-ui & mod-host

mod-ui 7978287085844ea4396dca1183ff1e2b1bc0b21b
mod-host 76ef52dc1ee461ca6c65dd478157e19b80fe708f

when performing change setting from midi separated mode to midi aggregated mode
then mod-ui crashes.

mod-ui log:
Cannot read socket fd = 10 err = Success
CheckRes error
JackSocketClientChannel read fail
websocket close
Jack server was closed but clients are still allocated, cleanup...
Cleanup client ref = 3
Server is not running
Server is not running
Cannot connect to server socket err = Connection refused
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

I think jackd crashes as well since I'm getting this line in jackd log:
JackGraphManager::Connect already connected port_src = 5 port_dst = 7

I think the same happens if I switch from a pedalboard using separated mode to a pedalboard using
aggregated mode.

Any clue?

Thanks,

**Comment by falkTX** [comment]
This is a jack crash, make sure to use 1.9.13 which has a fix for this.

**Comment by MaxPayne86** [comment]
> This is a jack crash, make sure to use 1.9.13 which has a fix for this.
